language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install: echo "not using cpanm!"
script: perl build.pl && ./Build test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
